language: node_js
node_js:
 - "8"
 
notifications:
  email: 
    false
before_install:
  - npm i -g npm@6.3.0

after_success:
  - npm run coveralls
  
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
    
